[package]
name = "rust-window"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.32.1"
imgui = "0.10.0"
imgui-glium-renderer = "0.10.0"
imgui-winit-support = "0.10.0"
